"""add workflow scheduling fields

Revision ID: b4c44ae395b9
Revises: ff8a3e6d47c6
Create Date: 2026-04-21 18:00:23.444086

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4c44ae395b9"
down_revision: Union[str, None] = "ff8a3e6d47c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflows", sa.Column("schedule_cron", sa.String(length=100), nullable=True))
    op.add_column("workflows", sa.Column("letta_schedule_id", sa.String(length=255), nullable=True))
    op.add_column("workflows", sa.Column("default_variables", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflows", "default_variables")
    op.drop_column("workflows", "letta_schedule_id")
    op.drop_column("workflows", "schedule_cron")
    # ### end Alembic commands ###
