"""add tool_ids skill_ids to workflows

Revision ID: d6855b645c78
Revises: 90446f55264d
Create Date: 2026-04-21 15:15:21.922374

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6855b645c78"
down_revision: Union[str, None] = "90446f55264d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflows", sa.Column("tool_ids", sa.Text(), nullable=True))
    op.add_column("workflows", sa.Column("skill_ids", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflows", "skill_ids")
    op.drop_column("workflows", "tool_ids")
    # ### end Alembic commands ###
